[package]
name = "tmfalloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.27", features = ["signal"] }
ctor = "0.2"
libc = "0.2"
errno = "0.3"
const-str = "0.5"
